import { Inter, Roboto, Inria_Serif, } from "next/font/google";
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const roboto = Roboto({ subsets: ["latin"], weight: ["100", "300", "400", "500", "700", "900"], variable: "--font-robot" });
const inriaSerif = Inria_Serif({ subsets: ["latin"], weight: ["300", "400", "700"], variable: "--font-inria-serif" });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export { inriaSerif, roboto, inter };